# Generated by Django 2.2.5 on 2019-10-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('palestrantes', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=30)),
                ('vagas_total', models.IntegerField()),
                ('vagas_restantes', models.IntegerField()),
                ('local', models.CharField(max_length=100)),
            ],
        ),
    ]
